'use client';
import type { Metadata } from 'next';
import Hero from '@/components/pages/home/hero';
import Project from '@/components/pages/home/project';
import Skill from '@/components/pages/home/skill';
import Profile from '@/components/pages/home/profile';
import Experiences from '@/components/pages/home/experiences';
import useSmoothScrollWheel from '@/lib/hooks/useSmothScrollWheel';
import { useRef } from 'react';

// export const metadata: Metadata = {
//    title: 'Create Next',
//    description: 'Generated by create next app',
// };

const Home = () => {
   const scrollRef = useRef<HTMLDivElement>(null);
   // useSmoothScrollWheel({ element: scrollRef });
   return (
      <div className="bg-ss flex h-full w-full items-center justify-center md:h-screen">
         <div className="relative m-3 h-full w-full max-w-6xl rounded-3xl backdrop-blur-md before:absolute before:-top-6 before:left-0 before:right-0 before:mx-auto before:h-6 before:w-10/12 before:rounded-t-xl before:bg-white/40 before:backdrop-blur-sm md:h-[calc(100vh_-_3rem)] md:bg-white/50 md:p-8 lg:mx-5 lg:h-[calc(100vh_-_12%)] lg:p-14">
            <div className="grid h-full w-full grid-cols-1 gap-5 md:grid-cols-3 lg:gap-12 lg:overflow-hidden">
               <div className="cols-span-1">
                  <Profile />
               </div>

               <div
                  ref={scrollRef}
                  className="overflow-y-bar-hide z-50 overflow-auto md:col-span-2">
                  <Hero />
                  <Skill />
                  <Experiences />
                  <Project />
               </div>
            </div>
         </div>
      </div>
   );
};
export default Home;
